baseURL = "https://tumblingpotato.org/"
languageCode = "en-us"
title = "Tumbling Potato"

[params]
  tagline = "A stealth organization"
  description = "Tumbling Potato — a stealth organization. Who can say what's going on?"

[taxonomies]
  tag = "tags"
  category = "categories"

[pagination]
  pagerSize = 20
